G0kU
ThaiProgrammer/code-mania-110 pull request #93
Opened 2017-11-26 02:45 UTC by natthakan159

Add information for WONGNAI INFARSTRUCTOR with Open Source

2017-11-26 18:17 UTC, dtinth requested changes
@natthakan159 Thanks for your contribution. Please check these comments:

2017-11-26 18:17 UTC, dtinth commented on Contributors.md
> +Name: Natthakan159
ไฟล์ Contributors.md ไม่ต้องใส่ก็ได้ครับเพราะเรามีหน้า [Contributors](https://github.com/ThaiProgrammer/code-mania-110/graphs/contributors) ของ GitHub อยู่แล้ว

2017-11-27 02:25 UTC, natthakan159 commented on Contributors.md
> +Name: Natthakan159
ขอบคุณครับ ผมชินไปหน่อย

2017-11-27 02:29 UTC, natthakan159 commented on Contributors.md
> +Name: Natthakan159
Please check again

2017-11-27 04:06 UTC, dtinth approved these changes

2017-11-27 04:06 UTC, merged

2017-11-27 04:06 UTC, dtinth commented
Thanks!